// <auto-generated />
namespace HS2231A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Finaldeployment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Finaldeployment));
        
        string IMigrationMetadata.Id
        {
            get { return "202308190303289_Final-deployment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
